<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Artikel_model extends CI_Model
{

    public $table = 'tbl_artikel';
    public $id    = 'artikel_id';
    public $order = 'DESC';
    public $slug  = 'artikel_slug';

    function __construct()
    {
        parent::__construct();
    }

    function make_id($huruf, $field, $table)
    {
        $cek    = $this->db->select("RIGHT($field,4) AS code", FALSE)->from($table)->order_by($field, 'DESC')->get()->row_array();

        $serial = $cek['code'] + 1;
        $code   = str_pad($serial, 4, '0', STR_PAD_LEFT);
        $kd     = $huruf . date('dmy') . $code;

        return $kd;
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get by slug
    function get_by_slug($slug = false)
    {
        if ($slug === false) {
            $this->get_all();
        }
        $this->db->where($this->slug, $slug);
        return $this->db->get($this->table)->row();
    }

    // get tag
    function get_tag()
    {
        $query = $this->db->distinct('artikel_tag')->select('artikel_tag')->get($this->table)->result();
        return $query;
    }

    function get_kategori()
    {
        $query = $this->db->distinct('artikel_kategori')->select('artikel_kategori')->get($this->table)->result();
        return $query;
    }

    function get_by_kategori($kategori)
    {
        $query = $this->db->where('artikel_kategori', $kategori)->get($this->table)->result();
        return $query;
    }

    function count_all_kategori($kategori)
    {
        $query = $this->db->where('artikel_kategori', $kategori)->get($this->table)->num_rows();
        return $query;
    }

    function get_archive()
    {
        $query = $this->db->query(" SELECT DISTINCT date_format('artikel_tanggal', '%M %Y') FROM $this->table")->result();
        return $query;
    }

    function get_by_archive($date)
    {
        $query = $this->db->query("SELECT * FROM $this->table WHERE artikel_tanggal between '$date-01' and '$date-31'")->result();
        return $query;
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('artikel_id', $q);
        $this->db->or_like('artikel_judul', $q);
        $this->db->or_like('artikel_isi', $q);
        $this->db->or_like('artikel_foto', $q);
        $this->db->or_like('artikel_tag', $q);
        $this->db->or_like('artikel_kategori', $q);
        $this->db->or_like('artikel_tanggal', $q);
        $this->db->or_like('artikel_slug', $q);
        $this->db->or_like('artikel_user', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('artikel_id', $q);
        $this->db->or_like('artikel_judul', $q);
        $this->db->or_like('artikel_isi', $q);
        $this->db->or_like('artikel_foto', $q);
        $this->db->or_like('artikel_tag', $q);
        $this->db->or_like('artikel_kategori', $q);
        $this->db->or_like('artikel_tanggal', $q);
        $this->db->or_like('artikel_slug', $q);
        $this->db->or_like('artikel_user', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Artikel_model.php */
/* Location: ./application/models/Artikel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-09 01:23:04 */
/* http://harviacode.com */
