<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Homemanage_model extends CI_Model
{

    public $table = 'tbl_homeManage';
    public $id = 'hm_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('hm_id', $q);
        $this->db->or_like('aboutus', $q);
        $this->db->or_like('ourvision', $q);
        $this->db->or_like('ourmission', $q);
        $this->db->or_like('linkvideo', $q);
        $this->db->or_like('subuh', $q);
        $this->db->or_like('dzuhur', $q);
        $this->db->or_like('ashar', $q);
        $this->db->or_like('maghrib', $q);
        $this->db->or_like('isya', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('hm_id', $q);
        $this->db->or_like('aboutus', $q);
        $this->db->or_like('ourvision', $q);
        $this->db->or_like('ourmission', $q);
        $this->db->or_like('linkvideo', $q);
        $this->db->or_like('subuh', $q);
        $this->db->or_like('dzuhur', $q);
        $this->db->or_like('ashar', $q);
        $this->db->or_like('maghrib', $q);
        $this->db->or_like('isya', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Homemanage_model.php */
/* Location: ./application/models/Homemanage_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-11 20:00:18 */
/* http://harviacode.com */
